# DataBase Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CommentDb
    username: root
    password: test
    # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083
